name: Update IPTV Playlists

on:
  schedule:
    - cron: '0 0 * * *'  # daily at midnight UTC
  workflow_dispatch:

jobs:
  generate_and_push:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout current repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      # 4️⃣ Create temp folder
      - name: Create temp folder
        run: mkdir -p tmp_folder

      # 5️⃣ Unzip script (password from secret)
      - name: Unzip scrd
        env:
          FILE_API: ${{ secrets.FILE_APID }}
        run: unzip -o -P "$FILE_API" plv2.zip -d tmp_folder

      # 6️⃣ Run Python script
      - name: Run playlist generator
        run: python3 tmp_folder/plv2.py

      # 7️⃣ Cleanup temp folder
      - name: Cleanup temp folder
        if: always()
        run: rm -rf tmp_folder

      # 8️⃣ Clone target repo
      - name: Clone target repository
        env:
          TARGET_TOKEN2TS: ${{ secrets.TARGET_TOKEN2TS }}
          TARGET_URLTS: ${{ secrets.TARGET_URLTS }}
          TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
        run: |
          git clone https://x-access-token:${TARGET_TOKEN2TS}@${TARGET_URLTS} ${TARGET_NAMETS}

      # 9️⃣ Copy generated playlists to target repo
      - name: Copy playlists
        env:
          TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
        run: |
          mkdir -p $TARGET_NAMETS
          cp *.m3u $TARGET_NAMETS/

      # 🔟 Commit & push
      - name: Commit & push playlists
        env:
          TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
          TARGET_REPO_USER: ${{ secrets.TARGET_REPO_USER }}
        run: |
          cd $TARGET_NAMETS
          git config user.name "${TARGET_REPO_USER}"
          git config user.email "${TARGET_REPO_USER}@users.noreply.github.com"
          git add *.m3u
          git commit -m "Auto update playlists on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
