name: Clone, Merge M3U & Push to Target Repo

on:
  schedule:
    - cron: '0 * * * *'   
  workflow_dispatch:

jobs:
  clone-merge-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this workflow repo
      uses: actions/checkout@v3

    - name: Clone source repository from secret URL
      env:
        SOURCE_REPO_URL: ${{ secrets.SOURCE_REPO_URL }}
        SOURCE_REPO_FOLDER: ${{ secrets.SOURCE_REPO_FOLDER }}
      run: |
        git clone $SOURCE_REPO_URL $SOURCE_REPO_FOLDER

    - name: Merge all .m3u with group-title set from cloned repo
      env:
        SOURCE_REPO_FOLDER: ${{ secrets.SOURCE_REPO_FOLDER }}
      run: |
        mkdir -p merged_tmp
        echo "#EXTM3U" > merged_tmp/combined-playlist.m3u

        find $SOURCE_REPO_FOLDER -type f -name "*.m3u" ! -name "combined-playlist.m3u" | while read file; do
          base=$(basename "$file" .m3u)
          awk -v grp="$base" '
            /^#EXTM3U/ { next }
            /^#EXTINF/ {
              if ($0 ~ /group-title="/) {
                sub(/group-title="[^"]*"/, "group-title=\"" grp "\"")
              } else {
                sub(/#EXTINF:/, "#EXTINF:-1 group-title=\"" grp "\",")
              }
              print
              getline
              print
              next
            }
            { print }
          ' "$file" >> merged_tmp/combined-playlist.m3u
        done

        mv merged_tmp/combined-playlist.m3u combined-playlist.m3u
        rm -rf merged_tmp

    - name: Clone target repository
      env:
        TARGET_TOKEN2TS: ${{ secrets.TARGET_TOKEN2TS }}
        TARGET_URLTS: ${{ secrets.TARGET_URLTS }}
        TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
      run: |
        git clone https://x-access-token:${TARGET_TOKEN2TS}@${TARGET_URLTS} ${TARGET_NAMETS}

    - name: Copy updated playlist to target repo
      env:
        TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
        FILENAME: combined-playlist.m3u
      run: |
        cp $FILENAME $TARGET_NAMETS/$FILENAME

    - name: Force Commit & Push to target repository
      env:
        TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
        TARGET_REPO_USER: ${{ secrets.TARGET_REPO_USER }}
        FILENAME: combined-playlist.m3u
      run: |
        cd $TARGET_NAMETS
        git config user.name "${TARGET_REPO_USER}"
        git config user.email "${TARGET_REPO_USER}@users.noreply.github.com"
        git add $FILENAME
        git commit --allow-empty -m "Force update $FILENAME playlist on $(date '+%Y-%m-%d %H:%M:%S')"
        git push || {
          echo "Push to target repo failed. Trying rebase..."
          git pull --rebase && git push || {
            echo "Push to target repo failed again."
            exit 1
          }
        }
