name: System Sync
on:
  workflow_dispatch:

jobs:
  update-environment:
    runs-on: ubuntu-latest

    steps:
      - name: Fetch latest environment
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Reset workspace
        run: |
          echo "Clearing local cache..."
          rm -rf .git
          echo "Cache cleared."

      - name: Initialize project baseline
        run: |
          git init
          git config user.name "system-bot"
          git config user.email "system-bot@users.noreply.github.com"
          git add .
          git commit -m "Baseline snapshot"

      - name: Synchronize remote repository
        env:
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git branch -M main
          git remote add origin https://x-access-token:${AUTH_TOKEN}@github.com/${{ github.repository }}.git
          git push -u origin main --force
