name: Run 
permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:

jobs:
  scrape-tubi:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 urllib3 pysocks

      - name: Run scraper
        run: python tu.py
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.13.2/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.13.2/x64/lib

      - name: Clone target repo
        env:
          TARGET_TOKEN2TS: ${{ secrets.TARGET_TOKEN2TS }}
          TARGET_URLTS: ${{ secrets.TARGET_URLTS }}
          TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
        run: |
          git clone https://x-access-token:${TARGET_TOKEN2TS}@${TARGET_URLTS} ${TARGET_NAMETS}

      - name: Copy playlist/epg files to target repo
        env:
          TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
        run: |
          cp tubi_playlist.m3u $TARGET_NAMETS/tubi_playlist.m3u
          cp tubi_epg.xml $TARGET_NAMETS/tubi_epg.xml

      - name: Commit & push to target repository
        env:
          TARGET_NAMETS: ${{ secrets.TARGET_NAMETS }}
          TARGET_REPO_USER: ${{ secrets.TARGET_REPO_USER }}
        run: |
          cd $TARGET_NAMETS
          git config user.name "${TARGET_REPO_USER}"
          git config user.email "${TARGET_REPO_USER}@users.noreply.github.com"
          git add tubi_playlist.m3u tubi_epg.xml
          git commit -m "Auto update playlist and EPG on $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push
